name: service_appointment
description: A Service Appointment Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  pigment: ^1.0.3
  flutter_svg: ^0.15.0
  feather_icons_flutter: ^4.7.4
  keyboard_avoider: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  vibrate: ^0.0.4
  intl: ^0.16.0
  tuple: ^1.0.3
  date_utils: ^0.1.0+3
  flutter_icons: ^1.0.0+1
  fluttertoast: ^3.1.3
  provider: ^4.0.1
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/transport_type/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-BlackItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ThinItalic.ttf
          weight: 300
          style: italic
































































































































































































































































































































































